#! /bin/sh

#--------swap CapsLock and Esc
xmodmap -e "clear Lock"         #or xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "keycode 66 = Escape"
xmodmap -e "keycode 9 = Caps_Lock"
xmodmap -e "keycode 65 = space"
xmodmap -e "add Lock = Caps_Lock"

#--------SpeedUp keyboard
xset r rate 190 40
#--------Don't let computer sleep
xset s 0 0
xset s off
#--------Wallpaper
xwallpaper --focus ~/.config/Wallpaper/wall.jpg

# fix cursor shape
xsetroot -cursor_name left_ptr

# to fix java applications
wmname LG3D
# to fix Android Studio
export _JAVA_AWT_WM_NONREPARENTING=1

# change default tmp dir
export TMPDIR="$HOME/storeDrive/storeDriveBig/Temp"


# launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# for Notifications
dunst &

#launch polybar
$HOME/.config/polybar/launch.sh

##############TESTING#################
## for HDMI
## https://www.youtube.com/watch?v=FAimFhf84QI
## https://www.reddit.com/r/archlinux/comments/1xx7d9/some_help_with_configuring_bspwm_multiple/

# if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
# 	xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-1 --mode 1366x768 --rotate normal
# fi
# bspc monitor eDP-1 -n 0 -d   3 4  6 7  
# bspc monitor HDMI-1 -n 0 -d   3 4  6 7  
##############TESTING#################

#set desktops
# src -> https://fontawesome.com/v4.7/cheatsheet/
# bspc monitor -d I II III IV V VI VII VIII IX
# bspc monitor -d     ♪          
# 𝟣 𝟤 𝟥 𝟦 𝟧 𝟨 𝟩 𝟪 𝟫
bspc monitor -d   3 4  6   


#window settings
bspc config border_width			1
bspc config window_gap				10
bspc config top_padding				10
bspc config bottom_padding			-5
# bspc config top_monocle_padding     10
# bspc config bottom_monocle_padding  -5
# bspc config left_monocle_padding    10
# bspc config right_monocle_padding   10

# colors
bspc config normal_border_color  "#1C1C1C"
bspc config urgent_border_color  "#ac8a8c"
bspc config focused_border_color "#505555"

bspc config split_ratio				0.55
bspc config borderless_monocle		false
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true

# colors
#source ~/.config/bspwm/theme

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating
bspc rule -a mpv state=floating follow=on focus=on rectangle=1000x600+185+100

bspc rule -a discord desktop='^7' follow=on focus=on
bspc rule -a Telegram-desktop desktop='^7' follow=on fstate=floating focus=on
bspc rule -a TelegramDesktop desktop='^7' follow=on state=floating focus=on

bspc rule -a zoom desktop='^7' follow=on state=floating focus=on
bspc rule -a root desktop='^7' follow=on state=floating focus=on
bspc rule -a Bspwm desktop='^7' follow=on state=floating focus=on

bspc rule -a Caprine desktop='^7' state=floating focus=on

bspc rule -a Eog state=floating follow=on focus=on
bspc rule -a Sxiv state=floating follow=on focus=on
bspc rule -a settings state=floating follow=on focus=on
bspc rule -a Guvcview state=floating follow=on focus=on
bspc rule -a guvcview state=floating follow=on focus=on
bspc rule -a Stremio desktop='^6' follow=on focus=on
bspc rule -a Gpick state=floating focus=on
bspc rule -a scrcpy state=floating focus=on

# XDM
bspc rule -a xdman-Main state=floating focus=on
# firefox pop-up window
bspc rule -a firefox follow=on state=floating focus=on
# tor browser
bspc rule -a "Tor Browser" follow=on state=floating focus=on
# brave
bspc rule -a Brave-browser follow=on state=floating focus=on
bspc rule -a brave-browser follow=on state=floating focus=on
# dolphin
bspc rule -a dolphin follow=on state=floating focus=on rectangle=666x724+150+50
# color picker
bspc rule -a ColorPicker follow=on state=floating focus=on
bspc rule -a color-picker follow=on state=floating focus=on
# wireshark
bspc rule -a Wireshark follow=on state=floating focus=on
# chrome
bspc rule -a Chromium-browser follow=on state=floating focus=on
# Virtual box
bspc rule -a "VirtualBox Manager" follow=on state=floating focus=on
bspc rule -a "VirtualBox Machine" follow=on state=floating focus=on
# blender
bspc rule -a Blender follow=on state=floating focus=on
# Jupyter
bspc rule -a urxvt follow=on state=floating focus=on
bspc rule -a URxvt follow=on state=floating focus=on
# sublime
bspc rule -a subl follow=on state=floating focus=on
bspc rule -a Subl follow=on state=floating focus=on

# xterm
bspc rule -a xterm follow=on state=floating focus=on
bspc rule -a XTerm follow=on state=floating focus=on
# for DearPyGui apps
bspc rule -a 'Dear PyGui' follow=on state=floating focus=on
bspc rule -a test follow=on state=floating focus=on
bspc rule -a lzdn follow=on state=floating focus=on
# for SFML
bspc rule -a sfml-app follow=on state=floating focus=on
# for zathura
bspc rule -a Zathura follow=on state=floating focus=on
bspc rule -a org.pwmt.zathura follow=on state=floating focus=on
# for qemu
bspc rule -a qemu state=floating
bspc rule -a Qemu-system-x86_64 state=floating
# tilix
bspc rule -a Terminator follow=on state=floating focus=on rectangle=1300x420+30+50
bspc rule -a terminator follow=on state=floating focus=on rectangle=1300x420+30+50
# okular
bspc rule -a okular follow=on state=floating focus=on
# nomacs
bspc rule -a nomacs follow=on state=floating focus=on
bspc rule -a "Image Lounge" follow=on state=floating focus=on
# Qute Browser
bspc rule -a qutebrowser follow=on state=floating focus=on
# krita
bspc rule -a krita qutefollow=on state=floating focus=on
# QT
bspc rule -a qtcreator qutefollow=on state=floating focus=on
bspc rule -a QtCreator qutefollow=on state=floating focus=on
# Logisim
bspc rule -a com-cburch-logisim-Main follow=on state=floating focus=on
# Pensela -- drawing on screen app
bspc rule -a pensela follow=on state=floating focus=on


# other
bspc rule -a Untitled follow=on state=floating focus=on



#window rules
bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Blueberry.py state=floating follow=on
bspc rule -a Iwgtk state=floating follow=on
bspc rule -a Steam desktop='^4' state=floating follow=on

