#!/bin/bash

function clamp {
  min=$1
  max=$2
  val=$3
  echo $((val > max ? max : val < min ? min : val))
}

direction=$1
current=$2
target=$(clamp 1 10 $((current + (direction == "down" ? 1 : -1))))
echo "jumping to $target"
hyprctl dispatch workspace $target
